name: yourscooks
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.6
  flutter_dotenv: ^5.2.1
  shared_preferences: ^2.5.2
  flex_color_scheme: ^8.1.0
  easy_splash_screen: ^1.0.4
  intl: ^0.20.0
  universal_html: ^2.2.4

  salomon_bottom_bar: ^3.3.2
  flutter_feather_icons: ^2.0.0+1
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.8.0
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.2.11
  draggable_home: ^1.0.5
  flutter_image_slideshow: ^0.1.6
  loadmore_listview: ^1.0.7

  crypto: ^3.0.6
  sign_in_with_apple: ^6.1.4
  google_sign_in: ^6.2.2
  flutter_facebook_auth: ^7.1.1

  firebase_core: ^3.11.0
#  firebase_database: ^11.3.0
  firebase_auth: ^5.4.2
  cloud_firestore: ^5.6.3

  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  dartz: ^0.10.1
  dartx: ^1.2.0

dev_dependencies:
  flutter_flavorizr: ^2.2.3
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.14
  flutter_gen_runner: ^5.9.0
  flutter_lints: ^5.0.0
  freezed: ^2.5.8
  json_serializable: ^6.9.3




# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
    ios:

  flavors:
    development:
      app:
        name: "DEV YoursCooks"

      android:
        applicationId: "id.mido.yourscooks.dev"
        variables:
          FLUTTER_TARGET:
            value: "lib/main.dart"

      ios:
        bundleId: "id.mido.yourscooks"
        variables:
          FLUTTER_TARGET:
            value: "lib/main.dart"

    production:
      app:
        name: "YoursCooks"

      android:
        applicationId: "id.mido.yourscooks"
        variables:
          FLUTTER_TARGET:
            value: "lib/main.dart"

      ios:
        bundleId: "id.mido.yourscooks"
        variables:
          FLUTTER_TARGET:
            value: "lib/main.dart"


flutter_gen:
  # Optional
  integrations:
    flutter_svg: true
    rive: false
    lottie: false

  assets:
    enabled: true
    outputs:
      class_name: AppImages
      package_parameter_enabled: false
      style: dot-delimiter

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/file/
    - assets/stickers/
    - assets/audio/
    - assets/fonts/
    - assets/vector/
